---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 30m
  timeout: 10m
  chart:
    spec:
      chart: metallb
      version: 0.15.2
      sourceRef:
        kind: HelmRepository
        name: metallb
      interval: 12h
  driftDetection:
    mode: enabled
  # https://github.com/metallb/metallb/blob/main/charts/metallb/values.yaml
  values:
    crds:
      enabled: true
