---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gitops
  namespace: default
spec:
  interval: 5m0s
  url: https://github.com/cthtrifork/pmx01-talos-gitops
  ref:
    branch: main
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitops-infra
spec:
  interval: 5m
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
  path: ./infra
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitops-infra-post
spec:
  interval: 5m
  prune: true
  sourceRef:
    kind: GitRepository
    name: gitops
  path: ./infra/post
