---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 12h
  url: oci://quay.io/cilium/charts/cilium
  ref:
    tag: 1.20.0
    digest: "sha256:8009baed89d99fd84f7ee5cfdbf3a1fae8153452132549833956b6aca8b9d738" # 1.19.3
