---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 12h
  url: oci://quay.io/cilium/charts/cilium
  ref:
    tag: 1.20.1
    digest: "sha256:906ce40d35daad838d12add8a5ba7033e767767f51799a93c7eace2cec9cdc05" # 1.19.3
