apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: allow-gha-controller-github-auth
  namespace: arc-runners-system
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    resourceNames: ["github-auth"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-gha-controller-github-auth
  namespace: arc-runners-system
subjects:
  - kind: ServiceAccount
    name: gha-runner-scale-set-controller-gha-rs-controller
    namespace: arc-controller-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: allow-gha-controller-github-auth
