apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: gha-rs-controller-namespace-admin
  namespace: arc-runners-system
rules:
  - apiGroups: ["rbac.authorization.k8s.io"]
    resources: ["roles", "rolebindings"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]

  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: gha-rs-controller-namespace-admin
  namespace: arc-runners-system
subjects:
  - kind: ServiceAccount
    name: gha-runner-scale-set-controller-gha-rs-controller
    namespace: arc-controller-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: gha-rs-controller-namespace-admin
