# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/service-v1.json
apiVersion: v1
kind: Service
metadata:
  name: adguard-dns
  namespace: adguard-system
  annotations:
    metallb.io/loadBalancerIPs: "192.168.1.253"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: adguard-home
  ports:
    - port: 53
      targetPort: 53
      name: dns-tcp
      protocol: TCP
    - port: 53
      targetPort: 53
      name: dns-udp
      protocol: UDP
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/service-v1.json
apiVersion: v1
kind: Service
metadata:
  name: zot.lan
  namespace: security-system
spec:
  type: ExternalName
  externalName: zot.registry-system.svc.cluster.local
