---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cert-manager
  namespace: default # todo
spec:
  interval: 30m
  timeout: 10m
  chart:
    spec:
      chart: cert-manager
      version: v1.18.2
      sourceRef:
        kind: HelmRepository
        name: cert-manager
      interval: 12h
  driftDetection:
    mode: enabled
  values:
    crds:
      enabled: true
    resources:
      requests:
        cpu: 50m 
        memory: 128Mi
      limits:
        memory: 256Mi
    webhook:
      resources:
        requests:
          cpu: 50m  
          memory: 128Mi  
        limits:
          memory: 256Mi 
    startupapicheck:
      resources:
        limits:
          memory: 32Mi
        requests:
          cpu: 50m  
          memory: 32Mi
    cainjector:
      resources:
        requests:
          cpu: 50m  
          memory: 128Mi  
        limits:
          memory: 256Mi 
    prometheus:
      enabled: false
      servicemonitor:
        enabled: false
    podDisruptionBudget:
      enabled: false
      maxUnavailable: 1
    replicaCount: 1
