# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/deployment-apps-v1.json
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-exporter
  namespace: adguard-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adguard-exporter
  template:
    metadata:
      labels:
        app: adguard-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9617"
    spec:
      containers:
        - name: exporter
          image: ebrianne/adguard-exporter:v1.14@sha256:44bb9e0e98f490e7e40c84461a38a59a41e03a21837b70105e048121e7962cb6
          ports:
            - containerPort: 9617
          env:
            - name: adguard_protocol
              value: "http"
            - name: adguard_hostname
              value: "adguard-web.adguard-system.svc.cluster.local"
            - name: adguard_username
              value: "admin"
            - name: adguard_password
              valueFrom:
                secretKeyRef:
                  name: adguard-credentials
                  key: password
            - name: adguard_port
              value: "80"
          resources:
            limits:
              memory: 128Mi
            requests:
              memory: 128Mi
              cpu: 10m
          securityContext:
            capabilities:
              drop:
                - "ALL"
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
            privileged: false
            runAsUser: 65534
            runAsGroup: 65534
