apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - deployment.yaml
  - pdb.yaml
  - adguard-exporter.yaml
  - service.yaml
  - secret.enc.yaml
  - namespace.yaml
configMapGenerator:
  - name: adguard-initial-config
    namespace: adguard-system
    files:
      - AdGuardHome.yaml=adguard-config.yaml
    options:
      disableNameSuffixHash: true
      labels:
        kyverno.io/watch: "true"

generatorOptions:
  disableNameSuffixHash: true
