apiVersion: v1
kind: Secret
metadata:
  name: adguard-credentials
  namespace: adguard-system
type: Opaque
stringData:
  password: ENC[AES256_GCM,data:AnEy0CGLDsQ=,iv:Tiluil4UbyeHrjgsv3VJ3LjLthMh2gOaUVl0yTuPNdA=,tag:NtXAaaRldUHmu3snIPozAA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUUJ4SVpJR29MN1BWWjNO
        V0c5VkNCMTFFQ29tWUg4MGt5ZEg1ZTFhREhvCmVDbHNGK1Y3TDY5TGtuWkVuUU1r
        cFhMQUF1WWVIN2FtRk5jUEduaE1XRmcKLS0tIFlrRE1SYVBSZ3NLVytSdkVYb0hH
        RGtYN0F2dFdqK3FXREZLMFBwUG1BbFEKC1USLJ0wfdcyQ0If0rKz9NXZ0HWoPCji
        esxyvy4nZvT0Rcw9yDUyvc7guVaISlxlShW7SfUSXbp67VchXRb7Iw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qth3nzg27zdmlzpjl2gedzmt0e5nly84q82knja3fcq365kw6u9qeecy6j
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-10T08:36:41Z"
  mac: ENC[AES256_GCM,data:edTNRTlf09xrFhudIPDaRA/q74xOAx2impCN7AdjEjBFUABMY9m8BpSBDhuLEoH7zHIOaBg/TAfTVLj90NHoV+nJKLSKWgF76QyD4Zz44aHqne0HyktT+zXWGXshvYt1TyFWVs1vwaKruEOwj2i1PTMTm33lo/dPEP4y6yR6550=,iv:XbdOUYFFCzONkQ6HzylLad/Wxs0MucWRG6I3syI61dM=,tag:8TpTflQaRi1eBQHciXizpA==,type:str]
  version: 3.13.0
