apiVersion: v1
kind: Service
metadata:
  name: adguard-dns
  namespace: adguard-system
  annotations:
    metallb.io/loadBalancerIPs: "192.168.1.253"
    lbipam.cilium.io/ips: "192.168.1.253"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: adguard-home
  ports:
    - port: 53
      targetPort: 53
      name: dns-tcp
      protocol: TCP
    - port: 53
      targetPort: 53
      name: dns-udp
      protocol: UDP
    - port: 443
      targetPort: 443
      name: https
    - port: 853
      targetPort: 853
      name: dns-tls
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-web
  namespace: adguard-system
  annotations:
    omni-kube-service-exposer.sidero.dev/label: "Adguard web portal"
    omni-kube-service-exposer.sidero.dev/port: "50086"
    omni-kube-service-exposer.sidero.dev/prefix: adguard
spec:
  type: ClusterIP
  selector:
    app: adguard-home
  ports:
    - port: 80
      targetPort: 3000
      name: http
