# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone-strict/statefulset-apps-v1.json
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: adguard-statefulset
  namespace: adguard-system
  annotations:
    reloader.stakater.com/auto: "true"
spec:
  serviceName: "adguard"
  replicas: 2
  selector:
    matchLabels:
      app: adguard-home
  template:
    metadata:
      labels:
        app: adguard-home
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - adguard-home
              topologyKey: "kubernetes.io/hostname" # Ensure 1 pod per node
      volumes:
        - name: initial-config
          configMap:
            name: adguard-initial-config
      initContainers:
        - name: copy-config
          image: busybox:1.37@sha256:1487d0af5f52b4ba31c7e465126ee2123fe3f2305d638e7827681e7cf6c83d5e
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
            - |
              set -e
              cp -vf /tmp/AdGuardHome.yaml /opt/adguardhome/conf/AdGuardHome.yaml
          volumeMounts:
            - name: adguard-config
              mountPath: /opt/adguardhome/conf
            - name: initial-config
              mountPath: /tmp/AdGuardHome.yaml
              subPath: AdGuardHome.yaml
          securityContext:
            capabilities:
              drop:
                - "ALL"
            readOnlyRootFilesystem: false
            allowPrivilegeEscalation: false
            privileged: false
            runAsUser: 65534
            runAsGroup: 65534
      containers:
        - name: adguard-home
          image: adguard/adguardhome:v0.107.74@sha256:f29c58a91f79387cbbbb042e140814f58e830d457d44af03d662c8df43db9dea
          ports:
            - containerPort: 53
              name: dns-tcp
              protocol: TCP
            - containerPort: 53
              name: dns-udp
              protocol: UDP
            - containerPort: 3000
              name: http
              protocol: TCP
            - containerPort: 443
              name: https
              protocol: TCP
            - containerPort: 853
              name: dns-tls
          volumeMounts:
            - name: adguard-data
              mountPath: /opt/adguardhome/work/ # AdGuard Runtime data
            - name: adguard-config
              mountPath: /opt/adguardhome/conf/ # AdGuard configuration
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              memory: 1Gi
          # livenessProbe:
          #   httpGet:
          #     path: /
          #     port: 3000
          #   initialDelaySeconds: 30
          #   periodSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /
          #     port: 3000
          #   initialDelaySeconds: 5
          #   periodSeconds: 5
  volumeClaimTemplates:
    - metadata:
        name: adguard-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
        storageClassName: "local-path"
    - metadata:
        name: adguard-config
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
        storageClassName: "local-path"
