---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: prometheus-community-kube-prometheus-stack
  namespace: kube-prometheus-stack-system
spec:
  interval: 12h
  url: oci://ghcr.io/prometheus-community/charts/kube-prometheus-stack
  ref:
    tag: 89.2.3
    digest: sha256:572ec345856aa3a4c3b7bce706dac997ea0d90944873025416db0c3b03dd2ed8
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: extract # can be 'extract' or 'copy', defaults to 'extract'
