---
apiVersion: v1
kind: Service
metadata:
  labels:
    kubevirt.io/vm: homeserver-vm
  name: homeserver-vm
  namespace: kubevirt-system
  annotations:
    metallb.universe.tf/address-pool: first-pool
spec:
  loadBalancerIP: 192.168.1.223 # todo
  externalTrafficPolicy: Local
  ipFamilyPolicy: SingleStack # IPv4
  ports:
    - name: ssh
      port: 22
      protocol: TCP
      targetPort: 22
  selector:
    kubevirt.io/vm: homeserver-vm
  type: LoadBalancer
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: homeserver-vm
  namespace: kubevirt-system
spec:
  #running: true
  runStrategy: Manual
  template:
    metadata:
      labels:
        kubevirt.io/vm: homeserver-vm
      #annotations:
      #  kubevirt.io/allow-pod-bridge-network-live-migration: "true"
    spec:
      #evictionStrategy: LiveMigrate
      domain:
        cpu:
          cores: 2
        resources:
          requests:
            memory: 32G
        devices:
          disks:
            - name: homeserver-vm-pvc
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
            - name: podnet
              masquerade: {}
      networks:
        - name: podnet
          pod: {}
      volumes:
        - name: homeserver-vm-pvc
          persistentVolumeClaim:
            claimName: homeserver-vm-pvc
        - name: cloudinitdisk
          cloudInitNoCloud:
            networkData: |
              network:
                version: 1
                config:
                  - type: physical
                    name: eno1 # eth0
                    subnets:
                      - type: dhcp
            userData: |-
              #cloud-config
              users:
                - name: cthtrifork
                  ssh_import_id:
                    - gh:cthtrifork
                  sudo: ['ALL=(ALL) NOPASSWD:ALL']
                  groups: sudo
                  shell: /bin/bash
  dataVolumeTemplates:
    - metadata:
        name: homeserver-vm-pvc
      spec:
        storage:
          resources:
            requests:
              storage: 256Gi
          accessModes:
            - ReadWriteOnce
          storageClassName: "local-path"
        source:
          http:
            secretRef:
              name: homeserver-download-secret
            url: "https://download.fedoraproject.org/pub/fedora/linux/releases/42/Cloud/x86_64/images/Fedora-Cloud-Base-Generic-42-1.1.x86_64.qcow2"
