---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: kyverno
  namespace: policy-system
spec:
  interval: 12h
  url: oci://ghcr.io/kyverno/charts/kyverno
  ref:
    tag: 3.8.0@sha256:ae87475ab2efedc133426c77228362e3d47234e76a3f7cfeced552666e6b3292
