---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 10m
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1 # retry indefinitely
  chart:
    spec:
      chart: cilium
      version: 1.17.6
      sourceRef:
        kind: HelmRepository
        name: cilium
  driftDetection:
    mode: enabled
  # https://github.com/cilium/cilium/blob/main/install/kubernetes/cilium/values.yaml
  values:
    ipam:
      mode: kubernetes
    kubeProxyReplacement: true
    securityContext:
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        cleanCiliumState:
          - NET_ADMIN
          - SYS_ADMIN
          - SYS_RESOURCE
    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup
    k8sServiceHost: localhost
    k8sServicePort: 7445

    # Multi-NIC: select all 'en*' devices across nodes (works with differing names)
    devices: "en+"
    nodePort:
      directRoutingDevice: "en+"

    # Reasonable bare-metal defaults
    #tunnel: "disabled"
    routingMode: "native"
    autoDirectNodeRoutes: true

    enableIPv4Masquerade: true
    ipMasqAgent:
      enabled: false
    ipv4NativeRoutingCIDR: "10.244.0.0/16"

    # Hubble (optional – observability)
    hubble:
      enabled: true
      relay:
        enabled: true
      ui:
        enabled: true