---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc-runners-homeserver-bootc
  namespace: arc-runners-system
spec:
  interval: 10m
  releaseName: arc-runners
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.13.0 # https://github.com/actions/actions-runner-controller/pkgs/container/actions-runner-controller-charts%2Fgha-runner-scale-set
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: arc-runners-system
  install:
    createNamespace: true
  # https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set/values.yaml
  values:
    controllerServiceAccount:
      # this SA is created by the controller chart, in arc-systems
      name: gha-runner-scale-set-controller
      namespace: arc-controller-system
    # name of the runner scale set -> what you use in `runs-on: arc-ubuntu`
    githubConfigUrl: https://github.com/cthtrifork/homeserver-bootc
    runnerScaleSetName: arc-ubuntu

    maxRunners: 5
    minRunners: 0

    # point to the secret we created with SOPS
    githubConfigSecret: github-auth

    # optional: labels to match on in your GitHub workflows
    containerMode:
      type: dind
    template:
      spec:
        initContainers:
          - name: init-dind-externals
            image: ghcr.io/actions/actions-runner:latest
            command:
              ["cp", "-r", "/home/runner/externals/.", "/home/runner/tmpDir/"]
            volumeMounts:
              - name: dind-externals
                mountPath: /home/runner/tmpDir
          - name: dind
            image: docker:dind
            args:
              - dockerd
              - --host=unix:///var/run/docker.sock
              - --group=$(DOCKER_GROUP_GID)
            env:
              - name: DOCKER_GROUP_GID
                value: "123"
            securityContext:
              privileged: true
            restartPolicy: Always
            startupProbe:
              exec:
                command:
                  - docker
                  - info
              initialDelaySeconds: 0
              failureThreshold: 24
              periodSeconds: 5
            volumeMounts:
              - name: work
                mountPath: /home/runner/_work
              - name: dind-sock
                mountPath: /var/run
              - name: dind-externals
                mountPath: /home/runner/externals
        containers:
          - name: runner
            image: ghcr.io/actions/actions-runner:latest
            command: ["/home/runner/run.sh"]
            env:
              - name: DOCKER_HOST
                value: unix:///var/run/docker.sock
              - name: RUNNER_WAIT_FOR_DOCKER_IN_SECONDS
                value: "120"
            volumeMounts:
              - name: work
                mountPath: /home/runner/_work
              - name: dind-sock
                mountPath: /var/run
        volumes:
          - name: work
            emptyDir: {}
          - name: dind-sock
            emptyDir: {}
          - name: dind-externals
            emptyDir: {}
