---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc-runners-homeserver-bootc
  namespace: arc-runners-system
spec:
  interval: 10m
  releaseName: arc-runners
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.13.0 # https://github.com/actions/actions-runner-controller/pkgs/container/actions-runner-controller-charts%2Fgha-runner-scale-set
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: arc-runners-system
  install:
    createNamespace: true
  # https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set/values.yaml
  values:
    controllerServiceAccount:
      # this SA is created by the controller chart, in arc-systems
      name: gha-runner-scale-set-controller-gha-rs-controller
      namespace: arc-controller-system
    # name of the runner scale set -> what you use in `runs-on: arc-ubuntu`
    githubConfigUrl: https://github.com/cthtrifork/homeserver-bootc
    runnerScaleSetName: arc-ubuntu

    maxRunners: 5
    minRunners: 1

    # point to the secret we created with SOPS
    githubConfigSecret: github-auth

    containerMode: {} # we use custom
    template:
      spec:
        initContainers:
          - name: init-dind-externals
            image: ghcr.io/cthtrifork/pmx01-talos-gitops/github-actions-runner:0.1.58
            imagePullPolicy: IfNotPresent
            command:
              ["cp", "-r", "/home/runner/externals/.", "/home/runner/tmpDir/"]
            volumeMounts:
              - name: dind-externals
                mountPath: /home/runner/tmpDir
          - name: dind
            image: public.ecr.aws/docker/library/docker:28.5.2-dind # mirror of docker official image
            imagePullPolicy: IfNotPresent
            args:
              - dockerd
              - --host=unix:///var/run/docker.sock
              - --group=$(DOCKER_GROUP_GID)
            env:
              - name: DOCKER_GROUP_GID
                value: "123"
            securityContext:
              allowPrivilegeEscalation: true
              privileged: true
              capabilities:
                add: ["SYS_ADMIN", "NET_ADMIN", "DAC_OVERRIDE", "CHOWN", "FOWNER", "SYS_RESOURCE"]
            restartPolicy: Always
            startupProbe:
              exec:
                command:
                  - docker
                  - info
              initialDelaySeconds: 0
              failureThreshold: 24
              periodSeconds: 5
            volumeMounts:
              - name: work
                mountPath: /home/runner/_work
              - name: dind-sock
                mountPath: /var/run
              - name: dind-externals
                mountPath: /home/runner/externals
              - name: docker-lib
                mountPath: /var/lib/docker
        containers:
          - name: runner
            image: ghcr.io/cthtrifork/pmx01-talos-gitops/github-actions-runner:0.1.58
            imagePullPolicy: IfNotPresent
            command: ["/home/runner/run.sh"]
            resources:
              requests:
                cpu: 100m
                memory: 2Gi
              limits:
                cpu: 4000m
                memory: 16Gi
            securityContext:
              privileged: true
              runAsUser: 1001
              runAsGroup: 1001
            env:
              - name: DOCKER_HOST
                value: unix:///var/run/docker.sock
              - name: RUNNER_WAIT_FOR_DOCKER_IN_SECONDS
                value: "120"
              - name: STORAGE_DRIVER
                value: overlay
              - name: BUILDAH_ISOLATION
                value: chroot
              - name: BUILDAH_LAYERS
                value: "true"
              #- name: BUILDAH_ISOLATION
              #  value: chroot
              #- name: STORAGE_DRIVER
              #  value: vfs
              #- name: _BUILDAH_STARTED_IN_USERNS
              #  value: ""
              #- name: _CONTAINERS_USERNS
              #  value: "auto"
              #- name: _CONTAINERS_USERNS_CONFIGURED
              #  value: ""
            volumeMounts:
              - name: container-storage
                mountPath: /var/lib/containers
              - name: work
                mountPath: /home/runner/_work
              - name: dind-sock
                mountPath: /var/run
              - name: container-rootless-storage
                mountPath: /home/runner/.local/share/containers/storage
              - name: container-mycontainers-storage
                mountPath: /var/lib/mycontainers
              - name: container-shared-storage
                mountPath: /var/lib/shared
              - name: docker-lib
                mountPath: /var/lib/docker
              - name: dnf-cache
                mountPath: /var/cache/dnf
              - name: dnf-cache
                mountPath: /home/runner/.cache/dnf
        imagePullSecrets:
          - name: github-auth
        securityContext:
          fsGroup: 1001
        volumes:
          - name: work
            ephemeral:
              volumeClaimTemplate:
                spec:
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: 32Gi
          - name: dind-sock
            ephemeral:
              volumeClaimTemplate:
                spec:
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: 1Gi
          - name: dind-externals
            ephemeral:
              volumeClaimTemplate:
                spec:
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: 10Gi
          - name: docker-lib
            emptyDir: {}
          - name: container-storage
            ephemeral:
              volumeClaimTemplate:
                spec:
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: 32Gi
          - name: container-rootless-storage
            ephemeral:
              volumeClaimTemplate:
                spec:
                  accessModes:
                    - ReadWriteOnce
                  resources:
                    requests:
                      storage: 16Gi
          - name: dnf-cache
            persistentVolumeClaim:
             claimName: arc-runner-dnf-cache
          - name: container-mycontainers-storage
            persistentVolumeClaim:
             claimName: container-mycontainers-storage
          - name: container-shared-storage
            persistentVolumeClaim:
             claimName: container-shared-storage
    listenerTemplate:
      spec:
        containers:
          - name: listener
            securityContext:
              runAsUser: 1000
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: arc-runner-dnf-cache
  namespace: arc-runners-system
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 24Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: container-shared-storage
  namespace: arc-runners-system
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 24Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: container-mycontainers-storage
  namespace: arc-runners-system
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 24Gi
