---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: arc-runners-homeserver-bootc
  namespace: arc-runners-system
spec:
  interval: 10m
  releaseName: arc-runners
  chart:
    spec:
      chart: gha-runner-scale-set
      version: 0.13.0 # https://github.com/actions/actions-runner-controller/pkgs/container/actions-runner-controller-charts%2Fgha-runner-scale-set
      sourceRef:
        kind: HelmRepository
        name: actions-runner-controller
        namespace: arc-runners-system
  install:
    createNamespace: true
  # https://github.com/actions/actions-runner-controller/blob/master/charts/gha-runner-scale-set/values.yaml
  values:
    controllerServiceAccount:
      # this SA is created by the controller chart, in arc-systems
      name: gha-runner-scale-set-controller-gha-rs-controller
      namespace: arc-controller-system
    # name of the runner scale set -> what you use in `runs-on: arc-ubuntu`
    githubConfigUrl: https://github.com/cthtrifork/homeserver-bootc
    runnerScaleSetName: arc-ubuntu

    maxRunners: 5
    minRunners: 1

    # point to the secret we created with SOPS
    githubConfigSecret: github-auth

    containerMode:
      type: dind
    template:
      spec:
        containers:
          - name: runner
            image: "ghcr.io/cthtrifork/pmx01-talos-gitops/github-actions-runner:latest"
            imagePullPolicy: Always
            command: ["/home/runner/run.sh"]
            resources:
              requests:
                cpu: 256m
                memory: 4Gi
              limits:
                cpu: 1000m
                memory: 8Gi
            securityContext:
              seLinuxOptions:
                type: spc_t
              privileged: true
              readOnlyRootFilesystem: false
              allowPrivilegeEscalation: true
              capabilities:
                add:
                  - SYS_ADMIN
                  - CAP_SYS_ADMIN # needed for podman dind
            env:
              - name: DOCKER_HOST
                value: unix:///var/run/docker.sock
              - name: RUNNER_WAIT_FOR_DOCKER_IN_SECONDS
                value: "120"
              - name: BUILDAH_ISOLATION
                value: chroot
              - name: STORAGE_DRIVER
                value: vfs
              - name: _BUILDAH_STARTED_IN_USERNS
                value: ""
              - name: _CONTAINERS_USERNS
                value: "auto"
            volumeMounts:
              - name: containers
                mountPath: /var/lib/containers
              - name: work
                mountPath: /home/runner/_work
              - name: dind-sock
                mountPath: /var/run
        # initContainers:
        #   - name: fix-storage-config
        #     image: "ghcr.io/cthtrifork/pmx01-talos-gitops/github-actions-runner:latest"
        #     imagePullPolicy: Always
        #     volumeMounts:
        #       - name: containers
        #         mountPath: /var/lib/containers
        #     args:
        #       - "bash"
        #       - "-c"
        #       - |
        #         sudo mkdir -p /etc/containers
        #         echo -e "[storage]\ndriver = \"overlay\"\nrunroot = \"/run/containers/storage\"\ngraphroot = \"/var/lib/containers/storage\"" \
        #           | sudo tee /etc/containers/storage.conf
        imagePullSecrets:
          - name: github-auth
        volumes:
          - name: work
            emptyDir: {}
          - name: containers
            emptyDir: {}
    listenerTemplate:
      spec:
        containers:
          - name: listener
            securityContext:
              runAsUser: 1000
