---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: arc-runners-system
  namespace: arc-runners-system
spec:
  interval: 12h
  layerSelector: # select the Helm chart layer
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  url: oci://ghcr.io/actions/actions-runner-controller-charts/gha-runner-scale-set
  ref:
    tag: "0.14.0"
