---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: kube-system
spec:
  interval: 5m
  timeout: 10m
  chart:
    spec:
      chart: metrics-server
      version: 3.13.0
      sourceRef:
        kind: HelmRepository
        name: metrics-server
      interval: 12h
  driftDetection:
    mode: enabled
  # https://github.com/kubernetes-sigs/metrics-server/blob/master/charts/metrics-server/values.yaml
  values:
    args:
      - --kubelet-insecure-tls
      - --kubelet-preferred-address-types=InternalIP
      - --metric-resolution=1m
      - --kubelet-request-timeout=30s
    serviceMonitor:
      enabled: true
    metrics:
      enabled: true
    resources:
      requests:
        cpu: 100m
        memory: 200Mi
      limits:
        cpu: 100m
        memory: 200Mi
    livenessProbe:
      failureThreshold: 15
      initialDelaySeconds: 60
      timeoutSeconds: 10
    readinessProbe:
      failureThreshold: 15
      initialDelaySeconds: 60
      timeoutSeconds: 10