---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 12h
  url: oci://quay.io/metallb/chart/metallb
  ref:
    tag: 0.16.1
    digest: "sha256:814c5ef92f9354238eabe52d6313a64a0ccfe52e9b941b0319202960e36e483e" # 0.15.3
