---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 12h
  url: oci://quay.io/metallb/chart/metallb
  ref:
    tag: 0.16.0
    digest: "sha256:302e71f9bbb04eb3289064130afb127710397bf67c12b8e73fb9cf063ac4b485" # 0.15.3
