---
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
containerdConfigPatches:
  - |-
    [plugins."io.containerd.grpc.v1.cri".registry]
      config_path = "/etc/containerd/certs.d"
networking:
  disableDefaultCNI: true
  #kubeProxyMode: none
  apiServerPort: 6443
  serviceSubnet: "10.96.0.0/16"
  podSubnet: "10.244.0.0/16"
  dnsSearch:
    - "default.svc.cluster.local"
    - "svc.cluster.local"
    - "cluster.local"
nodes:
  # == Control planes ==
  - role: control-plane
  # == Workers ==
  - role: worker
    # Extra port mappings are added to allow access to cluster services via localhost on the host machine.
    extraPortMappings:
      - containerPort: 443
        hostPort: 443
        protocol: TCP