---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cnpg
  namespace: storage-system
spec:
  interval: 12h
  url: oci://ghcr.io/cloudnative-pg/charts/cloudnative-pg
  ref:
    tag: 0.28.1
    digest: sha256:afa2aef55c6bf4297a0b8cbeb601a326d21892de94e92594657ec334e923fa67
