---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: cnpg
  namespace: storage-system
spec:
  interval: 12h
  url: oci://ghcr.io/cloudnative-pg/charts/cloudnative-pg
  ref:
    tag: 0.29.0
    digest: "sha256:209c588b902982bf283a0073db83edd422d9710a2c8a670fe57c0329abe789a4" # 0.28.0
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: extract # can be 'extract' or 'copy', defaults to 'extract'
