---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: reloader
  namespace: policy-system
spec:
  interval: 12h
  url: oci://ghcr.io/stakater/charts/reloader
  ref:
    tag: 2.2.12
    digest: sha256:1efe694acf4ada31404232a1889126ddc92789bddca3054f74f3b2e8ded1116a
