---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: reloader
  namespace: policy-system
spec:
  interval: 12h
  url: oci://ghcr.io/stakater/charts/reloader
  ref:
    tag: 2.2.17
    digest: sha256:cdaacb1aff0c01e7a580fef9f54a514825055badebdaa1f93c699e2e4aebb302
