apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-api-token-secret
  namespace: cert-manager-system
type: Opaque
stringData:
  api-token: ENC[AES256_GCM,data:efAi2Se/9GpAVwBYEXaJQClu0/g5Xz1MrAJbi5I0o38nUvLvM/NW9EccCmGhx9W5GZ7zxNQ=,iv:escyUqqztwESBKVnOJwYKI/ldt+Oafn72P4bzqgxI2w=,tag:bBdpLlPblrGs0OBbW1xDkA==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwaEJabjNFSDUrK1RwWUQr
        TWlHTDN3cEZ1YTRvZG5Hd0ttZXVYamZqbVJzCk1ZR0l5MzBDRW8xaXliRjZQN3JV
        b1MwSmNlS0dURFdQeGRKUWdSazRoZkkKLS0tIERSRXlmZkdDTndtWFVuT3BaY3pq
        bE5HVkNVeUZNTWFMNmFNOXlBS3dDbmMKrNOV6mmr7xQY4O2fJyRJ3un7aJpWFsPh
        uLzz5MKlG6OhC5+BS8xmsSMD/VT15np7pWneuy1aJjVY2hhx3ogeNw==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qth3nzg27zdmlzpjl2gedzmt0e5nly84q82knja3fcq365kw6u9qeecy6j
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-15T19:06:10Z"
  mac: ENC[AES256_GCM,data:jjoYU2d0GFxWVKo7LBYgGSaxpOH6pXiKA4Yp+A5r1Ox4xLBe0VZgmlB3r/g35wuRjuKT/3K7DklkZ3k7YXnftuLksW5MrgRRLKFV6HU7IlHwYD1iDr0HKNdYAnHb3yHlOJHdevu8PY4RLxzWroeHLt4ZmT6NE5XeCrfLERWLIQU=,iv:FsjI+egYLPUtQGfKOr48yXNFGh3IPEuZ6PXZIsRoIEU=,tag:+OQti5r9sgYlQ4462z6DsQ==,type:str]
  version: 3.13.0
