apiVersion: v1
kind: Service
metadata:
  name: flux-operator-exposed
  namespace: flux-system
  annotations:
    omni-kube-service-exposer.sidero.dev/label: Flux UI
    omni-kube-service-exposer.sidero.dev/port: "50080"
    omni-kube-service-exposer.sidero.dev/prefix: flux
  labels:
    app.kubernetes.io/instance: flux-operator
    app.kubernetes.io/name: flux-operator
spec:
  selector:
    app.kubernetes.io/instance: flux-operator
    app.kubernetes.io/name: flux-operator
  ports:
  - name: http-web
    port: 9080
    protocol: TCP
    targetPort: http-web
