name: Push Talos zot extension

on:
  pull_request: 
    branches: 
      - main
  push:
    branches:
      - main
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: read
  packages: write

env:
  IMAGE_NAME: talos-zot-extension
  ZOT_VERSION: "2.1.14" # todo renovatebot
  IMAGE: ghcr.io/${{ github.repository }}/talos-zot-extension

jobs:
  push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set image metadata
        id: meta
        run: |
          VERSION="${ZOT_VERSION}"

          {
            echo "image=${IMAGE}"
            echo "version=${VERSION}"
            echo "created=$(date -u +'%Y-%m-%dT%H:%M:%SZ')"
            echo "revision=${GITHUB_SHA}"
          } >> "${GITHUB_OUTPUT}"

      - name: replace VERSION in ext manifest
        run: sed -i "s/VERSION/${{ env.ZOT_VERSION }}/g" images/talos-zot-extension/manifest.yaml

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push extension image
        uses: docker/build-push-action@v6
        with:
          context: images/talos-zot-extension
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            ZOT_VERSION=${{ steps.meta.outputs.version }}
          tags: |
            ${{ steps.meta.outputs.image }}:${{ steps.meta.outputs.version }}
            ${{ steps.meta.outputs.image }}:latest
          labels: |
            org.opencontainers.image.title=Talos zot system extension
            org.opencontainers.image.description=zot OCI registry packaged as a Talos system extension
            org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
            org.opencontainers.image.revision=${{ steps.meta.outputs.revision }}
            org.opencontainers.image.created=${{ steps.meta.outputs.created }}

      - name: Create Installer
        env:
          IMAGE_EXT: ghcr.io/qjoly/talos.chaosd.extension/app:${{ env.APP_VERSION }}-${{ matrix.talos_version }}-${{ matrix.arch }}@${{ steps.build.outputs.digest }}
          ARCH: ${{ matrix.arch }}
          PROFILE: installer
        run: |
          docker run --rm -t -v /dev:/dev --privileged -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -v "$PWD/_out:/out" \
            "ghcr.io/siderolabs/imager:${{ matrix.talos_version }}" --arch "${ARCH}" \
            --system-extension-image ${IMAGE_EXT} "${PROFILE}"
          
      - name: Push installer
        if: ${{ github.event_name != 'pull_request' }}
        run: |
          docker load -i ./_out/installer-${ARCH}.tar
          docker tag ghcr.io/siderolabs/installer:${{ matrix.talos_version }} ghcr.io/${{ github.repository }}/talos.zot.extension/installer:${{ matrix.talos_version }}-${{ matrix.arch }}
          docker push ghcr.io/${{ github.repository }}/talos.zot.extension/installer:${{ matrix.talos_version }}-${{ matrix.arch }}

      - name: Create ISO
        if: ${{ github.event_name != 'pull_request' }}
        env:
          IMAGE_EXT: ghcr.io/qjoly/talos.chaosd.extension/app:${{ matrix.talos_version }}-${{ matrix.arch }}
          ARCH: ${{ matrix.arch }}
          PROFILE: iso
        run: |
          docker run --rm -t -v /dev:/dev --privileged -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -v "$PWD/_out:/out" \
            "ghcr.io/siderolabs/imager:${{ matrix.talos_version }}" --arch "${ARCH}" \
            --system-extension-image ${IMAGE_EXT} "${PROFILE}"

      - name: Upload a Build Artifact
        if: ${{ github.event_name != 'pull_request' }}
        uses: actions/upload-artifact@v6.0.0
        with:
          name: "${{ matrix.talos_version }}-${{ matrix.arch }}.iso"
          path: "_out/metal-${{ matrix.arch }}.iso"