name: test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ '*' ]
    tags-ignore: [ '*' ]

permissions:
    contents: read

jobs:
  manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Setup yq
        uses: fluxcd/pkg/actions/yq@1315c8aed1e3cc9bc0a6eb1f200ee571f8254525 # main
      - name: Setup kubeconform
        uses: fluxcd/pkg/actions/kubeconform@1315c8aed1e3cc9bc0a6eb1f200ee571f8254525 # main
      - name: Setup kustomize
        uses: fluxcd/pkg/actions/kustomize@1315c8aed1e3cc9bc0a6eb1f200ee571f8254525 # main
      - name: Validate manifests -- /apps
        run: ./scripts/validate.sh --dir apps
      - name: Validate manifests -- /infra
        run: ./scripts/validate.sh --dir infra
      - name: Validate manifests -- /clusters
        run: ./scripts/validate.sh --dir clusters