name: test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ '*' ]
    tags-ignore: [ '*' ]

permissions:
    contents: read

jobs:
  manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup yq
        uses: fluxcd/pkg/actions/yq@dfc427c54394de76e0053c2eba45699fad01c3b4 # main
      - name: Setup kubeconform
        uses: fluxcd/pkg/actions/kubeconform@dfc427c54394de76e0053c2eba45699fad01c3b4 # main
      - name: Setup kustomize
        uses: fluxcd/pkg/actions/kustomize@dfc427c54394de76e0053c2eba45699fad01c3b4 # main
      - name: Validate manifests -- /apps
        run: ./scripts/validate.sh --dir apps
      - name: Validate manifests -- /infra
        run: ./scripts/validate.sh --dir infra
      - name: Validate manifests -- /clusters
        run: ./scripts/validate.sh --dir clusters