name: test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ '*' ]
    tags-ignore: [ '*' ]

permissions:
    contents: read

jobs:
  manifests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
      - name: Setup yq
        uses: fluxcd/pkg/actions/yq@a12b6e8ae2242f78513537c9723c17b480188b8e # main
      - name: Setup kubeconform
        uses: fluxcd/pkg/actions/kubeconform@a12b6e8ae2242f78513537c9723c17b480188b8e # main
      - name: Setup kustomize
        uses: fluxcd/pkg/actions/kustomize@a12b6e8ae2242f78513537c9723c17b480188b8e # main
      - name: Validate manifests -- /apps
        run: ./scripts/validate.sh --dir apps
      - name: Validate manifests -- /infra
        run: ./scripts/validate.sh --dir infra
      - name: Validate manifests -- /clusters
        run: ./scripts/validate.sh --dir clusters