---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: zot
  namespace: registry-system
spec:
  interval: 12h
  url: oci://ghcr.io/project-zot/helm-charts/zot
  ref:
    tag: 0.1.114
    digest: sha256:15cf421da1822156d916c2d0d8842a45db321fba61fea674d7c716afdb9672e3
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: extract
