---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: zot
  namespace: registry-system
spec:
  interval: 12h
  url: oci://ghcr.io/project-zot/helm-charts/zot
  ref:
    tag: 0.1.113
    digest: sha256:700377efd5c6f20385de63ada21a73741ce12cbc8a23358dd336c2e93c1b610e
