---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/source.toolkit.fluxcd.io/ocirepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: zot
  namespace: registry-system
spec:
  interval: 12h
  url: oci://ghcr.io/project-zot/helm-charts/zot
  ref:
    tag: 0.1.116
    digest: sha256:8e83bfff8018aa306ca820eb74a7f2024b518be5254beaef16780e5543395cc7
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: extract
