apiVersion: v1
data:
  .dockerconfigjson: ENC[AES256_GCM,data:AYSKseD9GWVzt44ECqjARaCBTD07mGT7jZRfY6jInfGPTqfoeaqKn9RcyCl8SxBco1oWZcvrfFuWRuPKFLkebyNCDSnNZIPVI8K/1522XaCl7N8m6V5JtM/k46LmQtTA4r29PePfTZKtNZzq7doV6MYYeYzLp8M7sryJkLKaTjXKs86iGzpmU3RB0BRBUE8AqoqLT9JIvTIjlDoNrxDcl+vLUWKuonaXH67Fu3I1wjpGXLnTv+SayORIsYFuCltpXqHKN98NTgLGPGMvPTVIQ+/Eznf7YkrzKcJo0UjrhlibdzpHAvP9peEWa4UIVpwT9szwnOApw64EzfWoKtcOc+fFrQ4UsNYZr3RJJa1k22CW8PZQ,iv:EcdxfurHRoTTAIOYjFutbqrz991S3JJHNqZli5cPELU=,tag:fQhA27kNzYlb2DNJVus4BQ==,type:str]
kind: Secret
metadata:
  name: github-auth
type: kubernetes.io/dockerconfigjson
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvTUhpd05Rdk9ZWnQvdllG
        WFZidklkcWl6VGRTbTh3NDhIM055ZHR3em1ZCm1EdTQvQzhSNFlWcVRNbkl0NTFI
        MnFBdFRlVGhOVlBXQndVWUtzblJzRzgKLS0tIC9oamlpOHlTelJRYmkyQy9yQnhm
        SnJ1VnlkMTJ6b055bWpEZ2EwVTJCa2sKHrKWst9Fw5dNMSGKMvNUT8UOEsL4p2NO
        r2661BKAlPWN0eVQ5P5aoyvnMjNXEALfyXGI71/R0TDK/6y+F/C95A==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1qth3nzg27zdmlzpjl2gedzmt0e5nly84q82knja3fcq365kw6u9qeecy6j
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-05-27T10:21:04Z"
  mac: ENC[AES256_GCM,data:fi+nV04ofvqFA4oKhs/RjV8yFVWWXPrMzOGwVHC7qRUQFyzhgmhrZU5FCYCGLLOPNVpr8iPG815fSldWGXUPMQ5RTu/BxypsFGFdm+itnEUsKlg/bDIIlmNPEnlkpm/lIWvTIXd4Xc0GOmT68TjVl3Mw7CpfTBRlmcAgX2gbV7c=,iv:yWl4H6oBmFAOBCga1evNOl9Oo1YFxSq5LkmkQsIb2Uw=,tag:XYxU0xArzU92d5Zq1efodA==,type:str]
  version: 3.13.0
